In [3]:
import tensorflow as tf 
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [ ]:
#load the model and test

In [68]:
loaded_model = load_model('ann_model_new.h5')


In [46]:
with open('scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)
with open('label_encoder_gender.pkl', 'rb') as f:
    label_encoder = pickle.load(f)
with open('hot_encoder_geography.pkl', 'rb') as f:
    onehot_encoder = pickle.load(f)

In [24]:
input_data = {
    'CreditScore': 619.00,
    'Gender': 'Female',
    'Age': 42.00,
    'Tenure': 2.00,
    'Balance': 0.00,
    'NumOfProducts': 1.00,
    'HasCrCard': 1.00,
    'IsActiveMember': 1.00,
    'EstimatedSalary': 101348.88,
    'Geography'  :        'France'	
  
}


In [25]:
## encode one caterogical variables
from sklearn.preprocessing import LabelEncoder
input_data['Gender'] = label_encoder.transform([input_data['Gender']])[0]


In [26]:
input_data['Gender']

0

In [48]:
hot_encoded_data = onehot_encoder.transform([[input_data['Geography']]])
print(hot_encoded_data)


[[1. 0. 0.]]


c:\Users\sudee\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [49]:
hot_encoded_data


array([[1., 0., 0.]])

In [50]:
get_encoded_df = pd.DataFrame(hot_encoded_data, columns = onehot_encoder.get_feature_names_out(['Geography']))

In [51]:
get_encoded_df

Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [52]:
input_df = pd.DataFrame([input_data])

In [ ]:
final_input = pd.concat([input_df.reset_index(drop=True), get_encoded_df.reset_index(drop=True)], axis=1)


In [55]:
final_input

CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0        619.0       0  ...                0.0              0.0

[1 rows x 13 columns]

In [61]:
final_input.drop(['Geography'], axis=1, inplace=True)

In [57]:
input_df.head()

CreditScore  Gender   Age  ...  HasCrCard  IsActiveMember  EstimatedSalary
0        619.0       0  42.0  ...        1.0             1.0        101348.88

[1 rows x 9 columns]

In [64]:
input_scaled = scaler.transform(final_input)

In [65]:
input_scaled

array([[-0.33880827, -1.09499335,  0.29493847, -1.04241787, -1.21847056,
        -0.91668767,  0.64920267,  0.97481699,  0.01595384,  1.00150113,
        -0.57946723, -0.57638802]])

In [69]:
prediction = loaded_model.predict(input_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step


In [70]:
prediction

array([[0.3911646]], dtype=float32)

In [71]:
final_input.columns

Index(['CreditScore', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts',
       'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Geography_France',
       'Geography_Germany', 'Geography_Spain'],
      dtype='object')